Repository ANSHIKA-26/HelpingHands2.0, pull requests merged in 2024-06, with the labels that each got.

#57 Home UI enhanced
  images/home-img-2.jpg
  images/home-img.jpg
  index.css
  index.html
Labels: VSoC'24, MEDIUM

#58 Improved Register Page CSS and Fixed Post a Job button Bug
  assets/registerpage/image.png
  assets/registerpage/img1.jpg
  assets/registerpage/img10.jpg
  assets/registerpage/img2.png
  assets/registerpage/img3.jpg
  assets/registerpage/img4.jpg
  assets/registerpage/img5.jpg
  assets/registerpage/img6.jpg
  assets/registerpage/img7.jpg
  assets/registerpage/img8.jpg
  assets/registerpage/img9.jpg
  assets/registerpage/readme.md
  green.css
  green.html
  index.html
Labels: VSoC'24, MEDIUM

#49 backend: setup express and initial routes
  backend/.editorconfig
  backend/.gitignore
  backend/README.md
  backend/index.ts
  backend/package.json
  backend/schema.png
  backend/schema.sql
  backend/src/app.ts
  backend/src/database.ts
  backend/src/interfaces.d.ts
  backend/src/utils.ts
  backend/tsconfig.json
  backend/yarn.lock
Labels: BONUS, HARD, VSoC'24

#64 Updating .gitignore
  .gitignore
  .vscode/settings.json
Labels: 1-POINT
