Repository ANSHIKA-26/HelpingHands2.0, pull requests merged in 2024-07, with the labels that each got.

#75 Shifted Homepage to react
  frontend/package-lock.json
  frontend/package.json
  frontend/postcss.config.js
  frontend/public/index.html
  frontend/src/App.js
  frontend/src/components/Accordion/Accordion.js
  frontend/src/components/Home/Home.css
  frontend/src/components/Home/Home.js
  frontend/src/images/home-img.png
  frontend/src/index.css
  frontend/src/index.js
  frontend/tailwind.config.js
  images/home-img-2.jpg
  images/home-img.jpg
Labels: BONUS, VSoC'24

#83 React Navbar Creation
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/src/App.js
  frontend/src/components/Accordion/Accordion.js
  frontend/src/components/Home/Home.js
  frontend/src/components/Navbar/Navbar.js
  frontend/src/images/favicon.png
Labels: HARD, VSoC'24

#90 navbar and footer done.
  index.css
  index.html
Labels: VSoC'24, MEDIUM

#103 Creating a Terms & Conditions page
  Terms&Conditions.css
  Terms&Conditions.html
  index.html
Labels: MEDIUM
